# Compose file version
version: '3.8'

# Services, we have 2 services. 1 for the main app, and one for the database.
services:
  web:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8004:8000
    env_file: 
      - .env
    depends_on: 
      - web-db

  web-db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres