TEST_IN_DATA = [
    {'SalesID': 2676502, 'saleprice': 58000, 'model_id': 15461, 'data_source': 149, 'auctioneer_id': "27", 'year_made': 2008, 'machine_hours_current_meter': 1455, 'saledate': '2010-12-28', 'fi_model_desc': 'hl740tm7a', 'fi_base_model': 'hl740', 'fi_secondary_desc': 'tm', 'fi_model_series': '7', 'fi_model_descriptor': 'a', 'product_size': 'medium', 'state': 'north carolina', 'product_group': 'wl', 'product_group_desc': 'wheel loader', 'drive_system': "", 'enclosure': 'erops ac', 'ride_control': "", 'stick': "", 'transmission': "", 'engine_horsepower_desc': 'variable', 'hydraulics': '2 valve', 'ripper': "", 'tire_size': 20.5, 'coupler': "", 'hydraulics_flow': "", 'track_type': "", 'undercarriage_pad_width': 30.0, 'stick_length': "", 'grouser_type': "", 'blade_type': "", 'differential_type': 'standard', 'steering_controls': 'conventional', 'engine_horsepower': 142.5},
    
    {'SalesID': 2705977, 'saleprice': 60000, 'model_id': 28731, 'data_source': 149, 'auctioneer_id': "1", 'year_made': 2006, 'machine_hours_current_meter': 6088, 'saledate': '2010-07-15', 'fi_model_desc': 'wa320pt5l', 'fi_base_model': 'wa320', 'fi_secondary_desc': 'pt', 'fi_model_series': '5', 'fi_model_descriptor': 'l', 'product_size': 'medium', 'state': 'texas', 'product_group': 'wl', 'product_group_desc': 'wheel loader', 'drive_system': "", 'enclosure': 'erops ac', 'ride_control': "", 'stick': "", 'transmission': "", 'engine_horsepower_desc': 'variable', 'hydraulics': '2 valve', 'ripper': "", 'tire_size': 20.5, 'coupler': "", 'hydraulics_flow': "", 'track_type': "", 'undercarriage_pad_width': 30.0, 'stick_length': "", 'grouser_type': "", 'blade_type': "", 'differential_type': 'standard', 'steering_controls': 'conventional', 'engine_horsepower': 162.5},
    
    {'SalesID': 1447376, 'saleprice': 87000, 'model_id': 3362, 'data_source': 132, 'auctioneer_id': "6", 'year_made': 1987, 'machine_hours_current_meter': 3213, 'saledate': '1995-04-25', 'fi_model_desc': '140g', 'fi_base_model': '140', 'fi_secondary_desc': 'g', 'fi_model_series': "", 'fi_model_descriptor': "", 'product_size': 'small', 'state': 'new mexico', 'product_group': 'mg', 'product_group_desc': 'motor graders', 'drive_system': 'no', 'enclosure': 'erops', 'ride_control': "", 'stick': "", 'transmission': "", 'engine_horsepower_desc': 'variable', 'hydraulics': 'base + 1 function', 'ripper': 'yes', 'tire_size': 14.0, 'coupler': "", 'hydraulics_flow': "", 'track_type': "", 'undercarriage_pad_width': 30.0, 'stick_length': "", 'grouser_type': "", 'blade_type': "", 'differential_type': "", 'steering_controls': "", 'engine_horsepower': 157.5},
    
    {'SalesID': 1656917, 'saleprice': 10000, 'model_id': 11516, 'data_source': 132, 'auctioneer_id': "1", 'year_made': 1984, 'machine_hours_current_meter': 3213, 'saledate': '1993-11-18', 'fi_model_desc': 'fd7', 'fi_base_model': 'fd7', 'fi_secondary_desc': "", 'fi_model_series': "", 'fi_model_descriptor': "", 'product_size': "", 'state': 'texas', 'product_group': 'ttt', 'product_group_desc': 'track type tractors', 'drive_system': "", 'enclosure': 'orops', 'ride_control': "", 'stick': "", 'transmission': 'standard', 'engine_horsepower_desc': 'variable', 'hydraulics': '2 valve', 'ripper': "", 'tire_size': 20.0, 'coupler': "", 'hydraulics_flow': "", 'track_type': "", 'undercarriage_pad_width': 30.0, 'stick_length': "", 'grouser_type': "", 'blade_type': 'straight', 'differential_type': "", 'steering_controls': "", 'engine_horsepower': 80.0},
    
    {'SalesID': 1174711, 'saleprice': 8000, 'model_id': 9566, 'data_source': 121, 'auctioneer_id': "3", 'year_made': 1996, 'machine_hours_current_meter': 3213, 'saledate': '2004-12-16', 'fi_model_desc': '873', 'fi_base_model': '873', 'fi_secondary_desc': "", 'fi_model_series': "", 'fi_model_descriptor': "", 'product_size': "", 'state': 'georgia', 'product_group': 'ssl', 'product_group_desc': 'skid steer loaders', 'drive_system': "", 'enclosure': 'orops', 'ride_control': "", 'stick': "", 'transmission': "", 'engine_horsepower_desc': "", 'hydraulics': 'auxiliary', 'ripper': "", 'tire_size': 20.0, 'coupler': "", 'hydraulics_flow': 'standard', 'track_type': "", 'undercarriage_pad_width': 30.0, 'stick_length': "", 'grouser_type': "", 'blade_type': "", 'differential_type': "", 'steering_controls': "", 'engine_horsepower': 142.5}]


TEST_PREPROCESSED_DATA = [
    {'model_id': 15461, 'data_source': 149, 'auctioneer_id': 28, 'year_made': 2008, 'machine_hours_current_meter': 1455, 'fi_model_desc': 3086, 'fi_base_model': 1026, 'fi_secondary_desc': 146, 'fi_model_series': 79, 'fi_model_descriptor': 23, 'product_size': 4, 'product_group': 6, 'product_group_desc': 6, 'drive_system': 0, 'enclosure': 2, 'ride_control': 0, 'stick': 0, 'transmission': 0, 'engine_horsepower_desc': 1, 
    'hydraulics': 1, 'ripper': 0, 'tire_size': 20.5, 'coupler': 0, 'hydraulics_flow': 0, 'track_type': 0, 'undercarriage_pad_width': 30.0, 'stick_length': 0, 'grouser_type': 0, 'blade_type': 0, 'differential_type': 4, 'steering_controls': 2, 'saledate_year': 2010, 'saledate_month': 12, 'saledate_day': 28, 'saledate_dayofweek': 1, 'saledate_quarter': 4, 'engine_horsepower': 142.5, 
    'in_state_alabama': 0, 'in_state_alaska': 0, 'in_state_arizona': 0, 'in_state_arkansas': 0, 'in_state_california': 0, 'in_state_colorado': 0, 'in_state_connecticut': 0, 'in_state_delaware': 0, 'in_state_florida': 0, 'in_state_georgia': 0, 'in_state_hawaii': 0, 'in_state_idaho': 0, 'in_state_illinois': 0, 'in_state_indiana': 0, 'in_state_iowa': 0, 'in_state_kansas': 0, 'in_state_kentucky': 0, 'in_state_louisiana': 0, 'in_state_maine': 0, 'in_state_maryland': 0, 
    'in_state_massachusetts': 0, 'in_state_michigan': 0, 'in_state_minnesota': 0, 'in_state_mississippi': 0, 'in_state_missouri': 0, 'in_state_montana': 0, 'in_state_nebraska': 0, 'in_state_nevada': 0, 'in_state_new hampshire': 0, 'in_state_new jersey': 0, 'in_state_new mexico': 0, 'in_state_new york': 0, 'in_state_north carolina': 1, 'in_state_north dakota': 0, 'in_state_ohio': 0, 
    'in_state_oklahoma': 0, 'in_state_oregon': 0, 'in_state_pennsylvania': 0, 'in_state_puerto rico': 0, 'in_state_rhode island': 0, 'in_state_south carolina': 0, 'in_state_south dakota': 0, 'in_state_tennessee': 0, 'in_state_texas': 0, 'in_state_unspecified': 0, 'in_state_utah': 0, 'in_state_vermont': 0, 'in_state_virginia': 0, 'in_state_washington': 0, 'in_state_washington dc': 0, 'in_state_west virginia': 0, 'in_state_wisconsin': 0, 'in_state_wyoming': 0},
    
    {'model_id': 28731, 'data_source': 149, 'auctioneer_id': 2, 'year_made': 2006, 'machine_hours_current_meter': 6088, 'fi_model_desc': 4827, 'fi_base_model': 1860, 'fi_secondary_desc': 112, 'fi_model_series': 72, 'fi_model_descriptor': 61, 'product_size': 4, 'product_group': 6, 'product_group_desc': 6, 'drive_system': 0, 'enclosure': 2, 'ride_control': 0, 'stick': 0, 'transmission': 0, 'engine_horsepower_desc': 1, 
    'hydraulics': 1, 'ripper': 0, 'tire_size': 20.5, 'coupler': 0, 'hydraulics_flow': 0, 'track_type': 0, 'undercarriage_pad_width': 30.0, 'stick_length': 0, 'grouser_type': 0, 'blade_type': 0, 'differential_type': 4, 'steering_controls': 2, 'saledate_year': 2010, 'saledate_month': 7, 'saledate_day': 15, 'saledate_dayofweek': 3, 'saledate_quarter': 3, 'engine_horsepower': 162.5, 
    'in_state_alabama': 0, 'in_state_alaska': 0, 'in_state_arizona': 0, 'in_state_arkansas': 0, 'in_state_california': 0, 'in_state_colorado': 0, 'in_state_connecticut': 0, 'in_state_delaware': 0, 'in_state_florida': 0, 'in_state_georgia': 0, 'in_state_hawaii': 0, 'in_state_idaho': 0, 'in_state_illinois': 0, 'in_state_indiana': 0, 'in_state_iowa': 0, 'in_state_kansas': 0, 'in_state_kentucky': 0, 'in_state_louisiana': 0, 'in_state_maine': 0, 'in_state_maryland': 0, 
    'in_state_massachusetts': 0, 'in_state_michigan': 0, 'in_state_minnesota': 0, 'in_state_mississippi': 0, 'in_state_missouri': 0, 'in_state_montana': 0, 'in_state_nebraska': 0, 'in_state_nevada': 0, 'in_state_new hampshire': 0, 'in_state_new jersey': 0, 'in_state_new mexico': 0, 'in_state_new york': 0, 'in_state_north carolina': 0, 'in_state_north dakota': 0, 'in_state_ohio': 0, 
    'in_state_oklahoma': 0, 'in_state_oregon': 0, 'in_state_pennsylvania': 0, 'in_state_puerto rico': 0, 'in_state_rhode island': 0, 'in_state_south carolina': 0, 'in_state_south dakota': 0, 'in_state_tennessee': 0, 'in_state_texas': 1, 'in_state_unspecified': 0, 'in_state_utah': 0, 'in_state_vermont': 0, 'in_state_virginia': 0, 'in_state_washington': 0, 'in_state_washington dc': 0, 'in_state_west virginia': 0, 'in_state_wisconsin': 0, 'in_state_wyoming': 0},
    
    {'model_id': 3362, 'data_source': 132, 'auctioneer_id': 7, 'year_made': 1987, 'machine_hours_current_meter': 3213, 'fi_model_desc': 107, 'fi_base_model': 30, 'fi_secondary_desc': 58, 'fi_model_series': 0, 'fi_model_descriptor': 0, 'product_size': 6, 'product_group': 2, 'product_group_desc': 2, 'drive_system': 3, 'enclosure': 1, 'ride_control': 0, 'stick': 0, 'transmission': 0, 'engine_horsepower_desc': 1, 
    'hydraulics': 5, 'ripper': 3, 'tire_size': 14.0, 'coupler': 0, 'hydraulics_flow': 0, 'track_type': 0, 'undercarriage_pad_width': 30.0, 'stick_length': 0, 'grouser_type': 0, 'blade_type': 0, 'differential_type': 0, 'steering_controls': 0, 'saledate_year': 1995, 'saledate_month': 4, 'saledate_day': 25, 'saledate_dayofweek': 1, 'saledate_quarter': 2, 'engine_horsepower': 157.5, 
    'in_state_alabama': 0, 'in_state_alaska': 0, 'in_state_arizona': 0, 'in_state_arkansas': 0, 'in_state_california': 0, 'in_state_colorado': 0, 'in_state_connecticut': 0, 'in_state_delaware': 0, 'in_state_florida': 0, 'in_state_georgia': 0, 'in_state_hawaii': 0, 'in_state_idaho': 0, 'in_state_illinois': 0, 'in_state_indiana': 0, 'in_state_iowa': 0, 'in_state_kansas': 0, 'in_state_kentucky': 0, 'in_state_louisiana': 0, 'in_state_maine': 0, 'in_state_maryland': 0, 
    'in_state_massachusetts': 0, 'in_state_michigan': 0, 'in_state_minnesota': 0, 'in_state_mississippi': 0, 'in_state_missouri': 0, 'in_state_montana': 0, 'in_state_nebraska': 0, 'in_state_nevada': 0, 'in_state_new hampshire': 0, 'in_state_new jersey': 0, 'in_state_new mexico': 1, 'in_state_new york': 0, 'in_state_north carolina': 0, 'in_state_north dakota': 0, 'in_state_ohio': 0, 
    'in_state_oklahoma': 0, 'in_state_oregon': 0, 'in_state_pennsylvania': 0, 'in_state_puerto rico': 0, 'in_state_rhode island': 0, 'in_state_south carolina': 0, 'in_state_south dakota': 0, 'in_state_tennessee': 0, 'in_state_texas': 0, 'in_state_unspecified': 0, 'in_state_utah': 0, 'in_state_vermont': 0, 'in_state_virginia': 0, 'in_state_washington': 0, 'in_state_washington dc': 0, 'in_state_west virginia': 0, 'in_state_wisconsin': 0, 'in_state_wyoming': 0},
    
    {'model_id': 11516, 'data_source': 132, 'auctioneer_id': 2, 'year_made': 1984, 'machine_hours_current_meter': 3213, 'fi_model_desc': 2826, 'fi_base_model': 878, 'fi_secondary_desc': 0, 'fi_model_series': 0, 'fi_model_descriptor': 0, 'product_size': 0, 'product_group': 5, 'product_group_desc': 5, 'drive_system': 0, 'enclosure': 4, 'ride_control': 0, 'stick': 0, 'transmission': 6, 'engine_horsepower_desc': 1, 
    'hydraulics': 1, 'ripper': 0, 'tire_size': 20.0, 'coupler': 0, 'hydraulics_flow': 0, 'track_type': 0, 'undercarriage_pad_width': 30.0, 'stick_length': 0, 'grouser_type': 0, 'blade_type': 7, 'differential_type': 0, 'steering_controls': 0, 'saledate_year': 1993, 'saledate_month': 11, 'saledate_day': 18, 'saledate_dayofweek': 3, 'saledate_quarter': 4, 'engine_horsepower': 80.0, 
    'in_state_alabama': 0, 'in_state_alaska': 0, 'in_state_arizona': 0, 'in_state_arkansas': 0, 'in_state_california': 0, 'in_state_colorado': 0, 'in_state_connecticut': 0, 'in_state_delaware': 0, 'in_state_florida': 0, 'in_state_georgia': 0, 'in_state_hawaii': 0, 'in_state_idaho': 0, 'in_state_illinois': 0, 'in_state_indiana': 0, 'in_state_iowa': 0, 'in_state_kansas': 0, 'in_state_kentucky': 0, 'in_state_louisiana': 0, 'in_state_maine': 0, 'in_state_maryland': 0, 
    'in_state_massachusetts': 0, 'in_state_michigan': 0, 'in_state_minnesota': 0, 'in_state_mississippi': 0, 'in_state_missouri': 0, 'in_state_montana': 0, 'in_state_nebraska': 0, 'in_state_nevada': 0, 'in_state_new hampshire': 0, 'in_state_new jersey': 0, 'in_state_new mexico': 0, 'in_state_new york': 0, 'in_state_north carolina': 0, 'in_state_north dakota': 0, 'in_state_ohio': 0, 
    'in_state_oklahoma': 0, 'in_state_oregon': 0, 'in_state_pennsylvania': 0, 'in_state_puerto rico': 0, 'in_state_rhode island': 0, 'in_state_south carolina': 0, 'in_state_south dakota': 0, 'in_state_tennessee': 0, 'in_state_texas': 1, 'in_state_unspecified': 0, 'in_state_utah': 0, 'in_state_vermont': 0, 'in_state_virginia': 0, 'in_state_washington': 0, 'in_state_washington dc': 0, 'in_state_west virginia': 0, 'in_state_wisconsin': 0, 'in_state_wyoming': 0},

    {'model_id': 9566, 'data_source': 121, 'auctioneer_id': 4, 'year_made': 1996, 'machine_hours_current_meter': 3213, 'fi_model_desc': 1636, 'fi_base_model': 484, 'fi_secondary_desc': 0, 'fi_model_series': 0, 'fi_model_descriptor': 0, 'product_size': 0, 'product_group': 3, 'product_group_desc': 3, 'drive_system': 0, 'enclosure': 4, 'ride_control': 0, 'stick': 0, 'transmission': 0, 'engine_horsepower_desc': 0, 
    'hydraulics': 4, 'ripper': 0, 'tire_size': 20.0, 'coupler': 0, 'hydraulics_flow': 2, 'track_type': 0, 'undercarriage_pad_width': 30.0, 'stick_length': 0, 'grouser_type': 0, 'blade_type': 0, 'differential_type': 0, 'steering_controls': 0, 'saledate_year': 2004, 'saledate_month': 12, 'saledate_day': 16, 'saledate_dayofweek': 3, 'saledate_quarter': 4, 'engine_horsepower': 142.5, 
    'in_state_alabama': 0, 'in_state_alaska': 0, 'in_state_arizona': 0, 'in_state_arkansas': 0, 'in_state_california': 0, 'in_state_colorado': 0, 'in_state_connecticut': 0, 'in_state_delaware': 0, 'in_state_florida': 0, 'in_state_georgia': 1, 'in_state_hawaii': 0, 'in_state_idaho': 0, 'in_state_illinois': 0, 'in_state_indiana': 0, 'in_state_iowa': 0, 'in_state_kansas': 0, 'in_state_kentucky': 0, 'in_state_louisiana': 0, 'in_state_maine': 0, 'in_state_maryland': 0, 
    'in_state_massachusetts': 0, 'in_state_michigan': 0, 'in_state_minnesota': 0, 'in_state_mississippi': 0, 'in_state_missouri': 0, 'in_state_montana': 0, 'in_state_nebraska': 0, 'in_state_nevada': 0, 'in_state_new hampshire': 0, 'in_state_new jersey': 0, 'in_state_new mexico': 0, 'in_state_new york': 0, 'in_state_north carolina': 0, 'in_state_north dakota': 0, 'in_state_ohio': 0, 
    'in_state_oklahoma': 0, 'in_state_oregon': 0, 'in_state_pennsylvania': 0, 'in_state_puerto rico': 0, 'in_state_rhode island': 0, 'in_state_south carolina': 0, 'in_state_south dakota': 0, 'in_state_tennessee': 0, 'in_state_texas': 0, 'in_state_unspecified': 0, 'in_state_utah': 0, 'in_state_vermont': 0, 'in_state_virginia': 0, 'in_state_washington': 0, 'in_state_washington dc': 0, 'in_state_west virginia': 0, 'in_state_wisconsin': 0, 'in_state_wyoming': 0}
    ]