TEST_IN_DATA = {
    "saleprice": 58000,
    "model_id": 15461,
    "data_source": 149,
    "auctioneer_id": "27",
    "year_made": 2008,
    "machine_hours_current_meter": 1455,
    "saledate": "2010-12-28",
    "fi_model_desc": "hl740tm7a",
    "fi_base_model": "hl740",
    "fi_secondary_desc": "tm",
    "fi_model_series": "7",
    "fi_model_descriptor": "a",
    "product_size": "medium",
    "product_group": "wl",
    "state": "north carolina",
    "product_group_desc": "wheel loader",
    "drive_system": "",
    "enclosure": "erops ac",
    "ride_control": "",
    "stick": "",
    "transmission": "",
    "engine_horsepower_desc": "variable",
    "hydraulics": "2 valve",
    "ripper": "",
    "tire_size": 20.5,
    "coupler": "",
    "hydraulics_flow": "",
    "track_type": "",
    "undercarriage_pad_width": 30.0,
    "stick_length": "",
    "grouser_type": "",
    "blade_type": "",
    "differential_type": "standard",
    "steering_controls": "conventional",
    "engine_horsepower": 142.5,
}

TEST_PREPROCESSED_DATA = {
    "model_id": 15461,
    "data_source": 149,
    "auctioneer_id": 28,
    "year_made": 2008,
    "machine_hours_current_meter": 1455,
    "fi_model_desc": 3086,
    "fi_base_model": 1026,
    "fi_secondary_desc": 146,
    "fi_model_series": 79,
    "fi_model_descriptor": 23,
    "product_size": 4,
    "product_group": 6,
    "product_group_desc": 6,
    "drive_system": 0,
    "enclosure": 2,
    "ride_control": 0,
    "stick": 0,
    "transmission": 0,
    "engine_horsepower_desc": 1,
    "hydraulics": 1,
    "ripper": 0,
    "tire_size": 20.5,
    "coupler": 0,
    "hydraulics_flow": 0,
    "track_type": 0,
    "undercarriage_pad_width": 30.0,
    "stick_length": 0,
    "grouser_type": 0,
    "blade_type": 0,
    "differential_type": 4,
    "steering_controls": 2,
    "saledate_year": 2010,
    "saledate_month": 12,
    "saledate_day": 28,
    "saledate_dayofweek": 1,
    "saledate_quarter": 4,
    "engine_horsepower": 142.5,
    "in_state_alabama": 0,
    "in_state_alaska": 0,
    "in_state_arizona": 0,
    "in_state_arkansas": 0,
    "in_state_california": 0,
    "in_state_colorado": 0,
    "in_state_connecticut": 0,
    "in_state_delaware": 0,
    "in_state_florida": 0,
    "in_state_georgia": 0,
    "in_state_hawaii": 0,
    "in_state_idaho": 0,
    "in_state_illinois": 0,
    "in_state_indiana": 0,
    "in_state_iowa": 0,
    "in_state_kansas": 0,
    "in_state_kentucky": 0,
    "in_state_louisiana": 0,
    "in_state_maine": 0,
    "in_state_maryland": 0,
    "in_state_massachusetts": 0,
    "in_state_michigan": 0,
    "in_state_minnesota": 0,
    "in_state_mississippi": 0,
    "in_state_missouri": 0,
    "in_state_montana": 0,
    "in_state_nebraska": 0,
    "in_state_nevada": 0,
    "in_state_new hampshire": 0,
    "in_state_new jersey": 0,
    "in_state_new mexico": 0,
    "in_state_new york": 0,
    "in_state_north carolina": 1,
    "in_state_north dakota": 0,
    "in_state_ohio": 0,
    "in_state_oklahoma": 0,
    "in_state_oregon": 0,
    "in_state_pennsylvania": 0,
    "in_state_puerto rico": 0,
    "in_state_rhode island": 0,
    "in_state_south carolina": 0,
    "in_state_south dakota": 0,
    "in_state_tennessee": 0,
    "in_state_texas": 0,
    "in_state_unspecified": 0,
    "in_state_utah": 0,
    "in_state_vermont": 0,
    "in_state_virginia": 0,
    "in_state_washington": 0,
    "in_state_washington dc": 0,
    "in_state_west virginia": 0,
    "in_state_wisconsin": 0,
    "in_state_wyoming": 0,
}
